name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t wishwajith13/food-delivery .
      - name: Publish image to docker hub
        run: docker push wishwajith13/food-delivery:latest   

  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:
      - name: Pull image from docker hub
        run: docker pull wishwajith13/food-delivery:latest 
      - name: Delete Old Container
        run: docker rm -f foodDeliveryContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name foodDeliveryContainer wishwajith13/food-delivery   